env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  "comma-dangle": ["error", "only-multiline"],
  "indent": ["error", 2],
  "semi": ["error", "always"]
  "eol-last": ["error", "always"]
}
settings:
  react:
    version: detect